name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://mfe-samples/container/latest
        env:
          AWS_ACCESS_KEY_ID: AKIAZKWG2WXIHOTRGZRD
          AWS_SECRET_ACCESS_KEY: 62ZYZ12ajmzQKgY0Jli01jnRyMbiJCvnY5Z5c5ZQ
          AWS_DEFAULT_REGION: ap-southeast-1
      - run: aws cloudfront create-invalidation --distribution-id E3CAKP861975BM --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: AKIAZKWG2WXIHOTRGZRD
          AWS_SECRET_ACCESS_KEY: 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
          AWS_DEFAULT_REGION: ap-southeast-1
